{
 "title": "Acmeair JIT as a Service Demo Copy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Laptop #1: JDK8 OpenLiberty Server Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "OpenJ9 256MB",
     "measurement": "docker_container_mem_docker",
     "select": [
      [
       { "params": [ "total_rss" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "server_openj9" }
     ]
    },
    {
     "alias": "OpenJ9 NO_JIT 256MB + 256MB",
     "measurement": "mem_sum",
     "select": [
      [
       { "params": [ "mem_nojit_both" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Hotspot 256MB",
     "measurement": "docker_container_mem_docker",
     "select": [
      [
       { "params": [ "total_rss" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "server_hotspot" }
     ]
    }
   ]
  },
  {
   "title": "AcmeAir Reported Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "OpenJ9 256MB",
     "measurement": "jmeter_openj9.all.a.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ]
    },
    {
     "alias": "OpenJ9 NO_JIT 256MB + 256MB",
     "measurement": "jmeter_sum",
     "select": [
      [
       { "params": [ "jmeter_nojit_both" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ]
    },
    {
     "alias": "Hotspot 256MB",
     "measurement": "jmeter_hotspot.all.a.count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Laptop #1: JDK8 OpenLiberty Server CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "OpenJ9 256MB",
     "measurement": "docker_container_cpu_docker",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "server_openj9" }
     ]
    },
    {
     "alias": "Hotspot 256MB",
     "measurement": "docker_container_cpu_docker",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "server_hotspot" }
     ]
    },
    {
     "alias": "OpenJ9 NO_JIT 256MB + 256MB",
     "measurement": "cpu_sum",
     "select": [
      [
       { "params": [ "cpu_nojit_both" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Laptop 2: JIT Compiler Server CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "JIT Server",
     "measurement": "docker_container_cpu_docker",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "jitserver" }
     ]
    }
   ]
  }
 ]
}